/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecordRouteImport } from './routes/record'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AthletesRouteImport } from './routes/athletes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as SegmentIdRouteImport } from './routes/segment.$id'
import { Route as ClubIdRouteImport } from './routes/club.$id'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as AthleteIdRouteImport } from './routes/athlete.$id'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AthletesRoute = AthletesRouteImport.update({
  id: '/athletes',
  path: '/athletes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChallengesRoute,
} as any)
const SegmentIdRoute = SegmentIdRouteImport.update({
  id: '/segment/$id',
  path: '/segment/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubIdRoute = ClubIdRouteImport.update({
  id: '/club/$id',
  path: '/club/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChallengesRoute,
} as any)
const AthleteIdRoute = AthleteIdRouteImport.update({
  id: '/athlete/$id',
  path: '/athlete/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/onboarding': typeof OnboardingRoute
  '/record': typeof RecordRoute
  '/search': typeof SearchRoute
  '/segments': typeof SegmentsRoute
  '/training': typeof TrainingRoute
  '/activity/$id': typeof ActivityIdRoute
  '/athlete/$id': typeof AthleteIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/club/$id': typeof ClubIdRoute
  '/segment/$id': typeof SegmentIdRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRoute
  '/onboarding': typeof OnboardingRoute
  '/record': typeof RecordRoute
  '/search': typeof SearchRoute
  '/segments': typeof SegmentsRoute
  '/training': typeof TrainingRoute
  '/activity/$id': typeof ActivityIdRoute
  '/athlete/$id': typeof AthleteIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/club/$id': typeof ClubIdRoute
  '/segment/$id': typeof SegmentIdRoute
  '/challenges': typeof ChallengesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/athletes': typeof AthletesRoute
  '/auth': typeof AuthRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/clubs': typeof ClubsRoute
  '/onboarding': typeof OnboardingRoute
  '/record': typeof RecordRoute
  '/search': typeof SearchRoute
  '/segments': typeof SegmentsRoute
  '/training': typeof TrainingRoute
  '/activity/$id': typeof ActivityIdRoute
  '/athlete/$id': typeof AthleteIdRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/club/$id': typeof ClubIdRoute
  '/segment/$id': typeof SegmentIdRoute
  '/challenges/': typeof ChallengesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/athletes'
    | '/auth'
    | '/challenges'
    | '/clubs'
    | '/onboarding'
    | '/record'
    | '/search'
    | '/segments'
    | '/training'
    | '/activity/$id'
    | '/athlete/$id'
    | '/challenges/$id'
    | '/club/$id'
    | '/segment/$id'
    | '/challenges/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/athletes'
    | '/auth'
    | '/clubs'
    | '/onboarding'
    | '/record'
    | '/search'
    | '/segments'
    | '/training'
    | '/activity/$id'
    | '/athlete/$id'
    | '/challenges/$id'
    | '/club/$id'
    | '/segment/$id'
    | '/challenges'
  id:
    | '__root__'
    | '/'
    | '/athletes'
    | '/auth'
    | '/challenges'
    | '/clubs'
    | '/onboarding'
    | '/record'
    | '/search'
    | '/segments'
    | '/training'
    | '/activity/$id'
    | '/athlete/$id'
    | '/challenges/$id'
    | '/club/$id'
    | '/segment/$id'
    | '/challenges/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AthletesRoute: typeof AthletesRoute
  AuthRoute: typeof AuthRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  ClubsRoute: typeof ClubsRoute
  OnboardingRoute: typeof OnboardingRoute
  RecordRoute: typeof RecordRoute
  SearchRoute: typeof SearchRoute
  SegmentsRoute: typeof SegmentsRoute
  TrainingRoute: typeof TrainingRoute
  ActivityIdRoute: typeof ActivityIdRoute
  AthleteIdRoute: typeof AthleteIdRoute
  ClubIdRoute: typeof ClubIdRoute
  SegmentIdRoute: typeof SegmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/athletes': {
      id: '/athletes'
      path: '/athletes'
      fullPath: '/athletes'
      preLoaderRoute: typeof AthletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/segment/$id': {
      id: '/segment/$id'
      path: '/segment/$id'
      fullPath: '/segment/$id'
      preLoaderRoute: typeof SegmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club/$id': {
      id: '/club/$id'
      path: '/club/$id'
      fullPath: '/club/$id'
      preLoaderRoute: typeof ClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/athlete/$id': {
      id: '/athlete/$id'
      path: '/athlete/$id'
      fullPath: '/athlete/$id'
      preLoaderRoute: typeof AthleteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChallengesRouteChildren {
  ChallengesIdRoute: typeof ChallengesIdRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesIdRoute: ChallengesIdRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AthletesRoute: AthletesRoute,
  AuthRoute: AuthRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  ClubsRoute: ClubsRoute,
  OnboardingRoute: OnboardingRoute,
  RecordRoute: RecordRoute,
  SearchRoute: SearchRoute,
  SegmentsRoute: SegmentsRoute,
  TrainingRoute: TrainingRoute,
  ActivityIdRoute: ActivityIdRoute,
  AthleteIdRoute: AthleteIdRoute,
  ClubIdRoute: ClubIdRoute,
  SegmentIdRoute: SegmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
